version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tienda_vinilos
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./baseDeDatos:/docker-entrypoint-initdb.d

  api:
    build: ./vinil-svelte
    container_name: api_vinilos
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

volumes:
  pgdata: